asmbrobot/controller_manager:
  ros__parameters:
    update_rate: 50

    right_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

asmbrobot/right_group_controller:
  ros__parameters:
    joints:
      # - left_arm_joint1
      # - left_arm_joint2
      # - left_arm_joint3
      # - left_arm_joint4
      # - left_arm_joint5
      # - left_arm_joint6
      # - left_arm_joint7
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position

    allow_partial_joints_goal: true
