asmbrobot/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    right_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    asm_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

asmbrobot/right_group_controller:
  ros__parameters:
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      
    allow_partial_joints_goal: true