# This config file is used by ros2_control
asmbrobot/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    asmb_right_arm_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    asmb_right_arm_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

asmbrobot/asmb_right_arm_joint_trajectory_controller:
  ros__parameters:
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity