# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - hand_group_controller

  hand_group_controller:
    type: GripperCommand
    joints:
      - right_finger_joint1
      - right_finger_joint2
    action_ns: gripper_cmd
    default: true