# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_controller:
      type: position_controllers/GripperActionController


    left_hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
      - left_arm_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_hand_controller:
  ros__parameters:
    joints:
      - right_finger_joint1
      - right_finger_joint2
left_hand_controller:
  ros__parameters:
    joints:
      - left_finger_joint1
      - left_finger_joint2